import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Nav from '../components/Nav'
// import React from 'react'
// import { View, Text, Image, StyleSheet } from 'react-native'
// import { Svg } from 'react-native-svg'

// export default function LugStay() {
//   return (
//     <View style={Desktop9styles.desktop9}>
//       <View />
//     </View>
//   )
// }

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* 헤더 */}
      <Header />

      {/* 메뉴 */}
      <Nav />
      {/* 컨텐츠 */}
      {/* <Image 
        src=''
      /> */}
      
    </div>
  )
}